name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build
        pip install anytree systemdunitparser
    - name: Lint with flake8
      run: |
        pip install flake8
        cd systemdlint/systemdlint
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --ignore=E501,E261 --max-complexity=10 --max-line-length=127 --statistics
    - name: Build
      run: |
        cd systemdlint
        python -m build --sdist --wheel
    - name: Install
      run: |
        cd systemdlint
        python -m pip install --user dist/*.whl
    - name: Test
      run: |
        cd systemdlint
        $(pwd)/tests/test
      # Disable testing at 3.8 for now
      if: matrix.python-version != '3.8'
